config/routes.rb
Rails.application.routes.draw do
  resources :w2words
  resources :w1words
  resources :w0words
 get 'w0lookup', to: 'w0words#w0lookup'
  get 'w1lookup', to: 'w1words#w1lookup'
  get 'w2lookup', to: 'w2words#w2lookup'
  root :to => 'static_pages#crossroads'
   get 'home', to: 'static_pages#home'
   post 'whereto', to: 'static_pages#whereto'
   get 'crossroads', to: 'static_pages#crossroads'
   post 'crossroads', to: 'static_pages#crossroads'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/w0word.rb
class W0word < ApplicationRecord
    def self.search(search)
      
  where("category LIKE  ?", "%#{search.strip}%" ) 
end
end

app/models/w1word.rb
class W1word < ApplicationRecord
     def self.search(search)
  where("category LIKE  ?", "%#{search.strip}%" ) 
end
end

app/models/w2word.rb
class W2word < ApplicationRecord
     def self.search(search)
  where("category LIKE  ?", "%#{search.strip}%" ) 
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
# encoding: utf-8
class StaticPagesController < ApplicationController
    skip_before_action :verify_authenticity_token
  def home
  end
  def crossroads
  end
  def whereto
    goto = params[:name]
    case goto.downcase.strip
        when 'пизда'
      redirect_to w0lookup_path
      when 'хуй'
       redirect_to w1lookup_path
      when 'ебать'
      redirect_to w2lookup_path
      
    else
      
      redirect_to :controller=>'static_pages', :action=>'crossroads'
    end
  end
  
  
end

app/controllers/w0words_controller.rb
class W0wordsController < ApplicationController
  before_action :set_w0word, only: [:show, :edit, :update, :destroy]

  # GET /w0words
  # GET /w0words.json
  def index
     
     @w0words = W0word.all
  if params[:search]
    @w0words = W0word.search(params[:search]).order("created_at DESC")
  else
    @w0words = W0word.all.order("created_at DESC")
  end
  end

  # GET /w0words/1
  # GET /w0words/1.json
  def show
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_w0word
      @w0word = W0word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def w0word_params
      params.require(:w0word).permit(:expression, :interpretation, :usage_neutral, :usage_intense, :category, :category_definition, :synonym)
    end
end

app/controllers/w1words_controller.rb
class W1wordsController < ApplicationController
  before_action :set_w1word, only: [:show, :edit, :update, :destroy]

  # GET /w1words
  # GET /w1words.json
  def index
     
     @w1words = W1word.all
  if params[:search]
    @w1words = W1word.search(params[:search]).order("created_at DESC")
  else
    @w1words = W1word.all.order("created_at DESC")
  end
  end

  # GET /w1words/1
  # GET /w1words/1.json
  def show
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_w1word
      @w1word = W1word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def w1word_params
      params.require(:w1word).permit(:expression, :interpretation, :usage_neutral, :usage_intense, :category, :category_definition, :synonym)
    end
end

app/controllers/w2words_controller.rb
class W2wordsController < ApplicationController
  before_action :set_w2word, only: [:show, :edit, :update, :destroy]

  # GET /w2words
  # GET /w2words.json
  def index
     
     @w2words = W2word.all
  if params[:search]
    @w2words = W2word.search(params[:search]).order("created_at DESC")
  else
    @w2words = W2word.all.order("created_at DESC")
  end
  end

  # GET /w2words/1
  # GET /w2words/1.json
  def show
  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_w2word
      @w2word = W2word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def w2word_params
      params.require(:w2word).permit(:expression, :interpretation, :usage_neutral, :usage_intense, :category, :category_definition, :synonym)
    end
end

app/views/layouts/_footer.html.erb
 
 </div>
<div class="push"></div>
<p class="float_left"><a href="#top"><%= image_tag ("goup-left.gif")%>
		  вверх-скок
		  </a></p>
		  
		   <div id="volume_thumbs">
     <nav role="navigation" >
   
  <ul>
  <li><a href="http://sumizdut.narod.ru/volume-1/index.html">
  <%=image_tag "volume-1.png" %><br>
  том  1-й:
 <strong>  <br />личные творения</strong></a>
</li>

 <li  ><a href="http://sumizdut.narod.ru/volume-2/index.html">
   <%=image_tag "volume-2.png" %><br>
 том 2-й: <br /><strong>  литературные переводы</strong> </a>
</li>

 <li ><a href="http://sumizdut.narod.ru/volume-3/index.html">
   <%=image_tag "volume-3.png" %><br>
  том 3-й: <br /> <strong> научная беллетристика</strong> </a>
</li>

 <li ><a href="http://sumizdut.narod.ru/volume-4/index.html">
   <%=image_tag "volume-4.png" %><br>
  том 4-й: <br /> <strong> публицистика,  письма,<br /> ранние произведения</strong> </a>
</li>
<li ><a href="http://sumizdut.narod.ru/volume-5/index.html">
   <%=image_tag "volume-5.png" %><br>
  том 5-й: <br /> <strong> заключительный роман</strong> </a>
</li>
</ul>

</nav>
  </div>
 <footer role="contentinfo" ><p class="float_right"><a href="http://sumizdut.narod.ru/sitemap.html">карта сайта <%=image_tag "sitemap.png" %> </a>&nbsp;&nbsp;&nbsp;&nbsp;</p>
  <p >(Сopyleft&nbsp;&nbsp;;^)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <br /> сайт существует с 2002 г.; <br />переиздание 2015 г.,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2002 - <%=  Time.now.year %><br />
  с благодарностью всем вольным и невольным соавторам:<br />  землякам по планете и соучастникам по времени &ndash; <br />
  без вас ничего этого и не было бы;<br />
контакт:  ogoltsoff@gmail.com<br />&nbsp;
</p>
  </footer>
      

app/views/layouts/_header.html.erb
<a name="top"></a>
<div id="wrapper">
 
<header role="banner">
<span class="box_1 float_left">
      <br>
       <%= image_tag "shevron_small.gif", :style => 'float:left;' %>   
    
   <em >
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;пускай с моею мордою <br />
   &nbsp;&nbsp;&nbsp;печатных книжек нет, <br />
   &nbsp;&nbsp;вот эта блямба гордая <br />
   есть мой автопортрет
 </em>
 </span>
     <h1 class="box_2 reverse float_left">
    
    
     <br>мат 

 &nbsp;&nbsp;&nbsp;&nbsp;
     Стройбата 
     </h1>
    <h4 class=" white_shadow">
    <em>
    :авторский <br>сайт<br>графомана 
    </em>
    </h4>
     <strong class=" float_left">
     <em>р</em>укописи не горят<em>!..</em> ...в интернете ...&nbsp;&nbsp;&nbsp;
     </strong>
    <br>
       <nav role="navigation">
       
   
      <ul  >
        <li ><a href="http://sumizdut.narod.ru/index.html">главная полка</a></li>
        <li ><a href="http://sumizdut.narod.ru/volume-1/index.html" >&nbsp;том первый&nbsp;</a></li>
        <li><a href="http://sumizdut.narod.ru/volume-2/index.html">том второй</a></li>
        <li id="current"><a href="http://sumizdut.narod.ru/volume-3/index.html">том третий</a></li>
        <li><a href="http://sumizdut.narod.ru/volume-4/index.html">том четвёртый</a></li>
        <li><a href="http://sumizdut.narod.ru/volume-5/index.html">том пятый</a></li>
      </ul>
    

 </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>том третий: Научные Труды</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
  </body>
</html>

app/views/static_pages/crossroads.html.erb
 <div id="container" style="border-top:none;background-color:#ffffff;">
  
 
 
 
  &nbsp;<%= image_tag "dir.png",:style=>"float:left;width:200px;margin-top:3%;margin-left:3%;" %><br>
  
   <div id="box" style=" border-right:1px dashed 
silver;  margin-left:25%;margin-top:3%;">
<fieldset style="width:88%;text-align:center;"><legend style="float:left">
Сперва &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</legend> <p style="text-align:center;">о способе 
представления матерного материала.</p> <p style="text-align:center;">
Oн рассчитан на определённое содействие со стороны

пользователя данной базой данных, которая&mdash;ну, кто бы 
сомневался!&mdash;составлена из трёх частей (по числу <span 
id="span">w</span>-слов).</p>
<%= image_tag "w-word.png",:style=>"float:left;width:340px;" %>

<p> &nbsp;<br>&nbsp;&nbsp;Для входа в 
искомую часть набираем её корневое слово<em> (там, чуть пониже, есть специальное окошечко)</em> --
</p><p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span 
id="span">w0</span>, <span id="span">w1</span>, или <span 
id="span">w2</span>...
<br>(но, конечно ж, на руском)
<p>
<tt><b><i style="color:blue">(...чисто формальная проверка <br> 
&mdash;на всякий!&mdash;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
лингвистической зрелости &nbsp;&nbsp;пользователя:</i></b></tt>  <%= image_tag "lock.png",:style=>"float:right" %></p>



<%= form_tag('whereto') do -%>
  <br>
      <%= text_field_tag :name,nil,:placeholder=>'введите слово: w0, или w1, или w2 
',:size=>27,:style=>"margin-left:32%" %>
      <ul style="text-align:left;margin-left:86px;"><li>w0= сущ. жен. 
р., ед. ч., им. п.</li><li>w1= сущ. муж. р., ед. ч., им. п.</li><li>w2= 
глаг. неопр. фор., I спр. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em> (подробное определение<span id="span"> w-слов</span> смотри <span style="text-decoration:underline"> <%= link_to   "тут",home_path   %>)</span></em></li></ul>
   
      
<p style="text-align:center">

а после кликаем  вот эту кнопочку:<br>&nbsp;&nbsp;&nbsp;</p><p style="text-align:center">
<%= button_tag "эх, прокачу!", class: "button" %>
</p>
<% end -%>
<br>
 
 </fieldset>



<div class="roundbox" style="width:88%;float:left;margin-top: 5%;margin-left:-20%;margin-bottom:3%">
<div class="roundlegend" 
style="font-weight:bold;color:white;width:130px;margin-top:-28px; 
margin-left:10px;text-align:center;background:#000000;">Ежели в 
базе</div> 

<p style="padding:15px;clear:left">вам встретилась вопиющая неточность, 
или  у вас есть чем поделиться &ndash; милости просим!<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="mailto:ogoltsoff@gmail.com" style="text-align:center">Пишите</a>  <br>и вам ответится в течение трёх календарных дней.
</p><p style="padding-left:15px;clear:left"> Интересные выражения будут 
вставлены в саму базу, при условии их соответствия её тематике и 
моральным устоям: 

<ul style="text-align:left;margin-left:56px"><li> мир во всём мире, 
</li><li>равенство, дружба и братство всех народов</li><li>вольному 
&ndash; воля, спасённому &ndash; рай,</li><li> и т.д.</li></ul></p>
<p 
style=" color:#595;font-size:112%;text-align:center;position:relative; top:-60px;"><br>&nbsp;<br> 
Удачи всем:<br> как начинающим, так и заматерелым<br> филологам с 
филологиням, <br>и да пребудет с вами <span id="span">w2</span>ическая 
сила. 
</p>

</div><br>&nbsp;
</div><br>&nbsp;
	</div>		

app/views/static_pages/home.html.erb
 
 <aside>
 <br><br><br>
  <%=image_tag "achtung.png", :style => "width:88%;margin-left:18px;"%><br><br><br>
 </aside>
 
 <article>

<div id="box" style=" border-right:1px dashed 
silver;float:left">
<section style="text-align:left;">
 <h3 style="text-align:center"><br> поясниловка к базе данных<br>
 'мат стройбата'</h3>
<div style="width:78%;">
  <p style="width:78%;">Руский мат не вчера родился и, как любое выдержавшее проверку 
временем сооружение, зиждется на трёх китах.</p><p> 

Во-1-х, (джентельменски пропуская вперёд женский род) это &ndash; слово 
обозначающее женский половой орган, 

 скажем,  whale_0, а короче w0.



 </p><p> Вторым китом, натурально, становится слово 
используемое для наименования мужского полового органа, 

 его укоротим до w1.

  </p><p> Логическим  завершением, третьим членом данного 
китового стада &mdash;стало, есть и будет слово

  обозначающее естественное взаимодействие двух вышеперечисленных 
представителей данного основополагающего триумкитата &mdash; w2.<br>&nbsp;

  </p>

 <fieldset style=" "><legend>картинка 1:</legend> <p><em 
>Загадка истории &ndash; формула руского мата:<br> <br><span 
id="span">w0 + w1 = w2</span> <br><br>

 украшает мостовую средневекового итальянского 
дворика.</span></em></p><p><br>

<img alt="Xyz" src="/assets/xyz.jpg" style="align:center;width:100%;" />

</fieldset>

      	<p>

&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;

 В ходе исторического процесса носители языка неоднократно использовали 
все и каждое из трёх основных матерных слов для

обозначения объектов и явлений зачастую весьма удалённых от сферы 
межполового сношения.

	</p><p> 

	Употребления данных слов ["w0", "w1", "w2"] за пределами их 
прямого смысла, стирая изначальные значения, довёл их до   
многозначности на грани утраты всякого смысла, помимо передачи 
эмоционального состояния говорящего и исполнения одной из двух функций 
любого звукопроизводства любым живым существом: отпугнуть, или 
приманить.

		</p><p> 

Вместе с тем, присущая рускому языку система словообразования 
посредством смыслоносной пре-



и постфиксации привела к появлению от ровным счётом трёх



корней несметного числа матершинных производных  способных выразить 
тончайшие оттенки смысла.</p><p> 

В. Даль немало их, наверняка, встречал, но, придерживаясь правил 
приличия, скороговорочно определил мат как "площадную грубую брань". 
</p>

<p> 

А сказать по чести,

мат есть неотъемлемой&mdash;плоть от плоти&mdash;частью руского языка и 
чистоплюйские попытки разделить



язык на бранный и пристойный равносильны сегрегации людей по цвету 
кожи.</p>

  

  
 

<fieldset><legend>

    	картинка 2:</legend><p><em>Нарукавный шеврон<br> парадной 
формы<br> военных строителей..</em><br> <br> <div class='rotate_left polaroid'>
<%= image_tag "shevron.gif", :style => 'width:100%;', :class=> 'float_right' %> </div>
    	</fieldset>

    	 



  <p> За истёкшие век-полтора, мат так 

и остался табу – чем-то запретным к употреблению, кроме как в узком 
кругу закадычных приятелей. </p><p><i>(Правда, нынче  некоторые его 
составляющие нередко используют для увеселения публики.<br>

Когда табу &mdash;нечто общечтимое&mdash;шлёпается рылом в слякоть, то у 
определённой части населения вырывается здоровый хохот типа «бу-гы-гы!». 
Этим-то приёмом и кормятся господа хохмачи-телезатейники.)

</i></p>

  



 

<p> 



В конечном счёте, всё решает интонация &ndash; нейтральнейшее 
наименование произнесенное  с



презрением или ненавистью куда отвратней восхищённого матюка.</p>



<p> 

Язык, он не просто средство общения, а скорее набор инструментов для 
общения и увы мастеру, у



которого&mdash;в нужный момент&mdash;не окажется под рукой гвоздодёра 
или, там, шлямбура.</p>





<p> 

Важность мата для жизни любого вида:<br>&nbsp; <ul><table><tr><td 
valign="top"><li><span 
id="span">боевой</span></td><td>&nbsp;&nbsp;(<i>"...да я матом вышибал 
страх из людей и гнал под кинжальный огонь пулеметов!..</i>"), 
<br>&nbsp;</td></tr></table></li>

<table><tr><td valign="top"><li>

<span id="span">трудовой</span> </td><td>&nbsp;&nbsp;("<i>... с помощью 
зубила, молотка и распротакой матери побил все 
рекорды..."),</i><br>&nbsp;</td></tr></table></li>

<table><tr style="line-height:2.5em"><td style="line-height:2.5em" 
valign="top"><li><span id="span">половой</span> </td><td 
style="line-height:2.5em">&nbsp;&nbsp;(<i> стимулирующие качества мата в 
области любовных игр настолько неоспоримы, что я на 100%  согласен с 
наивным высказыванием будто в Советском Союзе не было секса &mdash; 
истинно, истинно говорю вам! &mdash; вместо секса  у нас была 
ебля),</i></td></tr></table></li></ul>

<p>

не требует долгих доказательств и  давно назрела необходимость 
повернуться к мату лицом и разобраться с ним как с лингвистической 
вариацией, вместо того, чтобы его замалчивать, зашикивать, 
поворачиваться спиной и прятать голову в песок &ndash; весьма (заметим к 
слову) неосмотрительная позиция, с учётом наличия хохмачествующих 
штукарей.

</p><p id="mat"> Mат, как любая иная грань языка, заслуживает уважения, 
философского осмысления,



фундаментальных исследований и популярного изложения.</p><p> 

B этом свете, база данных "мат стройбата" является 
эмпирио-хронологическим срезом матерной части руского



языка во второй половине ХХ века, в том виде, каковой она предстала 
автору этих строк в



королевских войсках Советской Армии (таким было  неофициальное название 
её военно-строительных отрядов, а короче &ndash; стройбатов, в 73-75 
г.г. прошлого века).



</p>



<div align="center"  >

<br>

<%= form_tag('crossroads') do -%>

 <%= button_tag  "введение в Мат Cтройбата",  class: "button" %>

 <% end -%>

     <p align="center">

 Приятно-полезного вам времяпрепровождения! <%=image_tag "shevron.gif", 
:style => "width:28px;"%> </p>	

  </div></div>
</div>
  </div></section></div>
</article>

app/views/w0words/index.html.erb
 
<div id="container" style="min-height:600px;">
<div class="push"></div> 
<p style="float:left; margin-left:1%;"><%= link_to 'новый поиск', w0lookup_path, 
:class=>'button' %></p>
 
<h1 style="color:red;text-align:center; width:56%;margin-left:20%" id="shadow"><em>корневое слово w0 и выражения от него</em><br>&nbsp;</h1>

<table  style="margin-right:1%;margin-left:1%;margin-top:3%" id="table">
<tbody>
  <thead>
    <tr style="color:#c30808;text-align:center; border-bottom:1px dashed silver;">
      <th> слово/выражение&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>его значение</th>
       <th width="9%">синонимы&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th width="5%">категория&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th width="43%">пояснение категории</th>
      <th    > 
примеры</th> 
    </tr>
    <tr ><th colspan=5></th></tr>
  </thead>

  <tbody>
    <% @w0words.each do |w0word| %>
      <tr class="<%= cycle('evenrow', 'oddrow') -%>">
        <td><%= w0word.expression %></td>
        <td><%= w0word.interpretation %></td>
         
         <td><%= w0word.synonym %></td>
        <td><%= w0word.category %></td>
        <td><%= w0word.category_definition %></td>
        <td><%= link_to 'покажь!', w0word %></td>
         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 

app/views/w0words/show.html.erb
<div id="container" style="min-height:544px;margin-top:3%">
<div class="push"></div>
<h5 style="color:brown" align="center"> примеры выражения <b>"<%= 
@w0word.expression 
%>":</b></h5>
<div align="center">
<h5 style="color:brown" align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>пример 1.</i></h5>
<p id="box" style="width:77%;border:1px dashed silver;text-align:left" >
  <%= @w0word.usage_neutral %>
</p>
</div>

<div class="push"></div>
<div align="center">
<h5 style="color:brown" align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>пример 2.</i></h5>
<p id="box" style="width:77%;border:1px dashed silver;text-align:left" >
  <%= @w0word.usage_intense %>
</p>
</div>
 
<div  class="polaroid rotate_right" 
style="width:52%;float:left; margin-left:10%;margin-top:3%;color:#000066;" 
 >

  <b>категория:</b><h5 style="display:inline;">
<%= @w0word.category  %>
</h5>
<p>
  <%= @w0word.category_definition %>
</p></div>
<div class="push"></div>
<div align="left" style="margin-bottom:3%;float:right;margin-right:20%">
<%= link_to 'новый поиск', w0lookup_path,:class=>"button" %>
</div>

app/views/w0words/w0lookup.html.erb
 
<div id="container" style="margin-top:3%;background-image:url(<%= image_path "glass.png" %>);background-repeat: no-repeat;">

<div   style="width:40%; float:right;margin-right:8%;margin-top:20px;clear:both;">
<p><strong>Информация для удобства пользователей базой:</strong></p>
Кнопка "покажь!" переносит к списку <strong>ВСЕХ</strong> выражений данного направления, откуда можно перейти к конкретным примерам их употребления</p>
<p>Список можно ограничить, если вместо "вали всё, что есть!" вписать/вставить наименование какой-либо из матерных категорий.</p>
<p style="width:453px;float:right; 
height:170px;margin-right:13px;color:#c30808;display:inline;font-size:110%;font-weight:bold;text-align:center;">
   
 наименования матерных категорий:
 <br>&nbsp;<br>прибаутки<br>прямосмыслы<br>смыслосмены<br>тех-подменки</p>
 
 </div>
 
 
<div style="width:60%; float:right;margin-right:10%;clear:both;">
<%= form_tag(w0words_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "вали всё, что есть!" %>
     
    <%= submit_tag "покажь!", :name => nil %>
<% end %>
 <div style="font-size:130%;color:#silver; margin-left:60%">
...или, может,
<h4 style="text-decoration:underline"> <%= link_to   "сменить корневое
слово?",crossroads_path   %><br>&nbsp;</h4>
</div>
 

 </div>
</div>
 
 
 

app/views/w1words/index.html.erb
 
<div id="container" style="min-height:600px;">
<div class="push"></div> 
<p style="float:left; margin-left:1%;"><%= link_to 'новый поиск', w1lookup_path, 
:class=>'button' %></p>
 
<h1 style="color:red;text-align:center; width:56%;margin-left:20%" id="shadow"><em>корневое слово w1 и выражения от него</em><br>&nbsp;</h1>

<table  style="margin-right:1%;margin-left:1%;margin-top:3%" id="table">
<tbody>
  <thead>
    <tr style="color:#c30808;text-align:center; border-bottom:1px dashed silver;">
      <th> слово/выражение&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>его значение</th>
       <th width="9%">синонимы&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th width="5%">категория&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th width="43%">пояснение категории</th>
      <th    > 
примеры</th> 
    </tr>
    <tr ><th colspan=5></th></tr>
  </thead>

  <tbody>
    <% @w1words.each do |w1word| %>
      <tr class="<%= cycle('evenrow', 'oddrow') -%>">
        <td><%= w1word.expression %></td>
        <td><%= w1word.interpretation %></td>
         
         <td><%= w1word.synonym %></td>
        <td><%= w1word.category %></td>
        <td><%= w1word.category_definition %></td>
        <td><%= link_to 'покажь!', w1word %></td>
         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 

app/views/w1words/show.html.erb
<div id="container" style="min-height:544px;margin-top:3%">
<div class="push"></div>
<h5 style="color:brown" align="center"> примеры выражения <b>"<%= 
@w1word.expression 
%>":</b></h5>
<div align="center">
<h5 style="color:brown" align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>пример 1.</i></h5>
<p id="box" style="width:77%;border:1px dashed silver;text-align:left" >
  <%= @w1word.usage_neutral %>
</p>
</div>

<div class="push"></div>
<div align="center">
<h5 style="color:brown" align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>пример 2.</i></h5>
<p id="box" style="width:77%;border:1px dashed silver;text-align:left" >
  <%= @w1word.usage_intense %>
</p>
</div>
 
<div  class="polaroid rotate_right" 
style="width:52%;float:left; margin-left:10%;margin-top:3%;color:#000066;" 
 >

  <b>категория:</b><h5 style="display:inline;">
<%= @w1word.category  %>
</h5>
<p>
  <%= @w1word.category_definition %>
</p></div>
<div class="push"></div>
<div align="left" style="margin-bottom:3%;float:right;margin-right:20%">
<%= link_to 'новый поиск', w1lookup_path,:class=>"button" %>
</div>